### PR TITLE
Org initiative

### PR DESCRIPTION
**Pull request by travislbrundage**
One database change: Journals are ManyToMany instead of ForeignKey

### CODE REVIEW

**Comment by garnertb** [comment]
Can you squash all of these when you're done?

**Comment by travislbrundage** [comment]
Squashed. You'll need to run the following in the db:

sudo -u postgres psql -d mapstory -c 'CREATE TABLE "mapstory_community_journals" (
    "id" serial NOT NULL PRIMARY KEY,
    "community_id" integer NOT NULL,
    "diaryentry_id" integer NOT NULL REFERENCES "mapstory_diaryentry" ("id") DEFERRABLE INITIALLY DEFERRED,
    UNIQUE ("community_id", "diaryentry_id")
)
;

CREATE TABLE "mapstory_task" (
    "id" serial NOT NULL PRIMARY KEY,
    "task" text NOT NULL,
    "community_id" integer NOT NULL REFERENCES "mapstory_community" ("id") DEFERRABLE INITIALLY DEFERRED
)
;
ALTER TABLE "mapstory_community" DROP COLUMN "link";
ALTER TABLE "mapstory_community" DROP COLUMN "journals_id";
ALTER TABLE "mapstory_community" ADD UNIQUE ("slug");
ALTER TABLE "mapstory_getpage" ADD UNIQUE ("name");

**Comment by travislbrundage** [comment]
Okay, the only way I could figure out how to do this correctly is to drop the entire table for mapstory_community.

1) In the database, run:
sudo -u postgres psql -d mapstory -c 'DROP TABLE "mapstory_community" CASCADE;'
2) Run syncdb
3) In the database, run:
sudo -u postgres psql -d mapstory -c 'ALTER TABLE "mapstory_community" ADD UNIQUE ("slug");
ALTER TABLE "mapstory_getpage" ADD UNIQUE ("name");'

Currently there are 3 community items that have been added which I believe will be lost.

**Comment by garnertb** [comment]
The syncdb needs to be able to reproduce the model with all of the constraints we expect (ie we shouldn't have to run step #3 after step #2).  I updated the community model to add the unique constraint to the name attribute.

**Pull request closed without merging**
