### PR TITLE
Update the default importer config to add permissions.

### PR DESCRIPTION
**Pull request by Coop56**
Updates the Importer Config to add layer styling permissions on import.  Based on this issue and it's comments: https://github.com/MapStory/mapstory/issues/851

### CODE REVIEW

**Comment by emilyashley** [comment]
Checked this out locally and I can confirm that the DEFAULT_IMPORTER_CONFIG makes it thru and joins the existing default_layer_config (i.e. always_geogig, editable). 

“change_layer_style” persists thru the importerController and wizardController and was available for checking in my layer perms (via `get_obj_perms`) on the layer detail page thru another registered user.

**Comment by emilyashley** [comment]
How do I confirm this addresses this issue at hand? @davisc ?

**Comment by Coop56** [comment]
@emilyashley You'll want to test to see if you can style newly imported layers, or if you run into permissions problems trying to do so.

**Comment by emilyashley** [comment]
@Coop56 I have other problems keeping me from getting to styling layers atm. I may need to nuke my whole set up.

**Review by davisc — APPROVED** [review]

**Pull request merged**
