### PR TITLE
Base testing

### LINKED ISSUE #408: Tests for Layer detail view
Unit testing for Layer detail views

### LINKED ISSUE #409: Tests for Layer create view
Unit tests for Layer create view

### LINKED ISSUE #427: Tests for Layer create
Unit tests for layer create view

### LINKED ISSUE #428: Layer importer tests
Tests for importer-api

### LINKED ISSUE #430: Fix boxes view tests
There is a bug with boxes attempting to commit a database transaction inside an atomic block. This is not allowed by Django. 

http://stackoverflow.com/questions/25370467/transactionmanagementerror-this-is-forbidden-when-an-atomic-block-is-active

### LINKED ISSUE #449: Update E2E Tests
Update and fix failing end-to-end tests.

### LINKED ISSUE #469: Setup automated browser testing on Travis
Need to :
- Configure travis to run automated browser tests.
- Setup selenium web-driver

### LINKED ISSUE #481: Testing profile views
Profile views need testing coverage

### LINKED ISSUE #484: Image-comparing tests
Create tests that use image comparison to serve as best-practice examples for other developers writing similar tests.

### LINKED ISSUE #486: Merge test branches
To avoid future merge conflicts

### LINKED ISSUE #561: Update browser tests for new Navigation
Need to update the tests to pass with the latest changes to navigation

### LINKED ISSUE #582: Update text to modal that appears just before you publish a story is not correct
Just before a user publishes a story, they see this warning message:

screen shot 2017-03-31 at 1 00 28 pm

Now that we have the ability to make changes to a published story and re-publish, this text is not correct.

For time being, change text to:

"Great work! Once you hit publish everyone will be able to search for your story. Don't worry, after you publish your story you can make changes to it anytime and publish an updated version. You can always delete it too."

### LINKED ISSUE #627: Update tests for latests changes
Some tests have to be updated to work with the latest changes.

### PR DESCRIPTION
**Pull request by josellausas**
This pull request merges two previous pull requests: #472 and #429

- Closes #486
- Closes #408
- Closes #481
- Closes #409
- Closes #469
- Closes #449
- Closes #430
- Closes #427
- Closes #428
- Closes #484
- Closes #561 
- Closes #627 
- Closes #582

### CODE REVIEW

**Comment by josellausas** [comment]
Tests are not passing because Geonode is not configured on Travis.  Need #384 and #490 before tests can pass.

**Comment by cuttlefish** [comment]
It's currently failing because it's attempting to pull the geoserver `public_url`. We can either change this to the private url, or give the django container the CA certificate we use for signing the certificates for test. Or both.

**Comment by cuttlefish** [comment]
It seems to be failing deleting some databases
`django.db.utils.OperationalError: database "test_mapstory_geogig" is being accessed by other users
DETAIL:  There are 2 other sessions using the database.`

**Comment by cuttlefish** [comment]
The issue seems to be that geoserver is maintaining a connection to the database.
I'm looking into solutions.

**Comment by josellausas** [comment]
Merged latest master branch and have to update some tests.
Closes #627

**Comment by josellausas** [comment]
Commented out automated tests and created an issue for the problem: #656 

Automated tests are not working with the Docker setup. I'm creating a separate issue so we can merge the unit tests that are currently passing.

screen shot 2017-04-25 at 12 04 45 pm

**Review by cuttlefish — COMMENTED** [review]
At long last, I've got coveralls working.
The test coverage has gone down somewhat, but some of the tests have been disabled.
I think we should get it merged in, I don't like having important branches around this long.

**Review by cuttlefish — APPROVED** [review]

**Pull request merged**
