### PR TITLE
Search design fixes; Very MVP initiative/org pages

### PR DESCRIPTION
**Pull request by travislbrundage**
This may require some db changes/updates... I got this to work on my machine just be restarting gunicorn.

The notable changes include changing Community's name field to a SlugField and making it unique, and adding a few new views.

### CODE REVIEW

**Comment by travislbrundage** [comment]
I updated it to just use an additional slug field for now. Still need to look into how to slugify the name appropriately, but this should work fine also, it's just being manually set instead.

databse update commands:
ALTER TABLE "mapstory_community"
	ADD COLUMN "slug" varchar(64) NOT NULL;
ALTER TABLE "mapstory_community"
	ADD COLUMN ("slug");
ALTER TABLE "mapstory_community"
	ADD UNIQUE ("slug");
CREATE INDEX "mapstory_community_slug"
	ON "mapstory_community" ("slug");
CREATE INDEX "mapstory_community_slug_like"
	ON "mapstory_community" ("slug" varchar_pattern_ops);

**Comment by garnertb** [comment]
Manually setting a slug is a non-starter.  Use a signal to programmatically set it: https://docs.djangoproject.com/en/1.6/topics/signals/, example: https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L737.

**Comment by travislbrundage** [comment]
Thanks for the feedback - I seem to have messed something up in my git, I'll get the commit to fix this up soon

**Comment by travislbrundage** [comment]
ALTER TABLE "mapstory_community" ADD COLUMN "slug" varchar(64) NOT NULL;
ALTER TABLE "mapstory_community" ADD UNIQUE ("slug");
CREATE INDEX "mapstory_community_slug" ON "mapstory_community" ("slug");
CREATE INDEX "mapstory_community_slug_like" ON "mapstory_community" ("slug" varchar_pattern_ops);

I think that should be good for slug now. Testing on my local VM and it works as expected. It'll generate the slug based on the name.

**Pull request merged**
