### PR TITLE
Testing instructions

### PR DESCRIPTION
**Pull request by josellausas**
- Added instructions to README.md.
- Added missing test layer files.
- Added signup form tests.

### CODE REVIEW

**Comment by Coop56** [comment]
Since we're splitting the unit tests up into their own app directories (see the journal directory as an example) - is there a way we can run one command that will find and run all tests in all apps at once?  @zunware?

**Comment by zunware** [comment]
We can do that by importing tests inside `tests/__init__.py` . We can run: `python manage.py test mapstory.tests` and it will run all tests imported inside the file.

I think adding `from ..journal.tests import *` to that file will do the trick. I will be testing it and let you if it works.

**Comment by Coop56** [comment]
Part of the style guide I'm working on includes not adding anything to the __init.py__ file. Is there another way to do it?

**Comment by Coop56** [comment]
Test discovery is based on the unittest module’s built-in test discovery. By default, this will discover tests in any file named “test*.py”.

From the docs ^.  So it looks like if we just run python manage.py test it should auto discover and run all of the tests.

**Comment by zunware** [comment]
It seems that `manage.py tests` is not finding and running the tests like it should. I did some research and came across this: 

According to: http://stackoverflow.com/questions/2037364/django-test-runner-not-finding-tests ,
nose has problems because the vm flags the files as executables.

The workaround is to do this: http://stackoverflow.com/a/6249739/1078537

**Pull request merged**
