### PR TITLE
Geonode 2.7 update

### PR DESCRIPTION
**Pull request by Coop56**
This branch gets us up to date with the latest 2.7.x branch of Geonode.

### CODE REVIEW

**Comment by lhcramer** [comment]
@cuttlefish, @Coop56:  What is the status of this PR. Is it critical path for code complete deadline on the 28th?

**Comment by Coop56** [comment]
Not critical for the code completion deadline on the 28th no - we need to allot time at some point to finish reviewing this PR and get it merged in.  There's been changes to 2.7 since this PR was first introduced so we'll likely need to do additional work as well.  cc @lhcramer @cuttlefish

**Comment by Coop56** [comment]
Closing this PR.  2.8 is out now which is a release version vs. 2.7 which was a development version.  Since this never got merged in before, we may as well bump straight to 2.8.

**Comment by cuttlefish** [comment]
please, no one hit delete on the branch. we need that.

**Comment by Coop56** [comment]
I backed this branch up onto my fork already @cuttlefish. https://github.com/Coop56/mapstory/tree/geonode-2.7-update

**Pull request closed without merging**
