### PR TITLE
Update host variables to ensure all environments are using the correct values.

### PR DESCRIPTION
**Pull request by Coop56**
Update host variables to ensure all environments are using the correct values.

### CODE REVIEW

**Comment by cuttlefish** [comment]
LGTM. Have we tried actually running them on prod and demo yet?

**Comment by Coop56** [comment]
@cuttlefish Yes they've both run.  All seems well, but @davisc download this branch and take a look at the settings if you could please just to be sure.

**Comment by davisc** [comment]
@Coop56 will do.

**Comment by Coop56** [comment]
@davisc I created an RDS instance for demo and just updated this PR to include it in the host_vars for demo.

**Review by davisc — APPROVED** [review]

**Pull request merged**
