### PR TITLE
Change the story routes so that they contain a story title slug

### PR DESCRIPTION
**Pull request by Coop56**
This PR contains several changes all relating to changing our story routes.  All stories will now have a slug that is a slugified version of the title.  This gets updated anytime a story is saved, so if the title is changed the slug will be as well.

The routes will now be /story/story-id-number/story-title-slugified.

If a user goes to just /story/story-id-number I've setup a function to ensure it redirects to the correct full path.  Part of the requirements given to me were to keep the ID number in the URL route.  I don't think this is necessary, and it clutters up the URL but it's there as per the requirements.  I'm open to changing how I've done the routes if anyone has any feedback.

### CODE REVIEW

**Comment by sarasafavi** [comment]
@Coop56 is there a reason we're keeping that ID number in the URI? From what I understand here we're using uniquified slugs, so we shouldn't need to keep an ID number in the mix at all. From a user standpoint it seems it would be easier to just type/verbally share/etc a pronounceable URI without numbers.

**Comment by cuttlefish** [comment]
Yeah, I don't quite understand either. If the desire is to make the URLs visibly unique, maybe `/story/username-or-orgname/story-title-slugified` or `/username-or-orgname/story/story-title-slugified` would be better? It's a bit odd that layers and stories have different schemes.

I'd thought that the ID numbers were just to support old stories (which should be easy enough). If they're supposed to do something else, I'm very unclear what it is.

**Comment by Coop56** [comment]
@marino would have to chime in on the requirements.  I had a solution for making the URLs unique in the case of two titles being identical I added the ID number of the story onto the end. `/story/story-title-slugified-story-id` The ID would only be appended onto the end in the case of an identical slug already existing.  

That seems a lot better than having an ID number in the URL route all the time.  ID numbers are also setup to redirect to the full URL so that wouldn't be an issue either.  We could easily add usernames if we wanted to.  

Currently the slug changes anytime the title does, we could stop that from happening if we wanted but I don't see it being a problem.  I assume once a user is happy with their title they'll stop changing it and they'll want the URL to reflect the final title.

**Comment by jonpmarino** [comment]
i think the thinking was that 1) many stories will have similar names, like "Scramble for Africa" or "Battle of Gettysburg" so the number gives something unique that a teacher could use to specify which story they want their students to bring up, or a use case like that. 

Also 2) What happens when an author changes the story name after it is published, which they could do? At least a number would give you an evergreen reference for the story even as the story name changes. Sort of like having a Dewey Decimal pasted on a book title at the old library.

Also, if we did /username-or-orgname/story-title-slugified what happens when a story has more than one author? This isn't possible now but will be someday down the road (i.e. #876).

I like Jeremiah's suggestion of only adding the number if there is another story with the same name. But what happens if when the story is created there is no other story with the same name, but someone later changes their story to a name that does already exist? Would a number then get dynamically added ex post facto? If so, that would work.

Having a number makes us similar to the way Scribd (https://www.scribd.com/book/235411767/A-Man-Called-Ove-A-Novel), Stackoverflow (https://stackoverflow.com/questions/45423650/own-version-of-string-copy-in-c-causing-segmentation-fault) and Medium (https://medium.com/@creative_ian/the-age-of-the-creative-f32370301528) do it. 

I think we also did the same format for layers and stories on retro, but would have to see retro to confirm. I agree having the same model for layers and stories makes sense.

That was the thinking anyway. If all devs feel strongly that those platforms are doing it wrong and agree on a different best practice, I'm cool with it. This isn't huge on my priority list compared to other things so am happy to talk to Chris about it.

**Comment by Coop56** [comment]
My opinion stays the same - `/layer/layer-name-slug` and `/story/story-name-slug`.  Duplicates get checked every time a story is saved, so if someone changed their story name to something that duplicated another story already existing, the story that was just saved would add the ID on.  

I'm open to other thoughts on duplicates.  We could just not allow them, we can add the ID on at the end `/story/story-name-slug-id` or we could add just an incrementing number `/story/story-name-slug-1` etc.

I'm sure there are other ways to handle duplicates as well.

**Pull request closed without merging**
