### PR TITLE
Updated all urls to allow a trailing /

### PR DESCRIPTION
**Pull request by travislbrundage**

### CODE REVIEW

**Comment by travislbrundage** [comment]
Messed up my git branch so had to open a new PR identical to #157.

**Comment by travislbrundage** [comment]
So, I added some very simple tests for pinging the updated urls. There are a few odd cases where I'm not sure I'm able to test this way due to a specific workflow or purpose for that link. Here's the ones that aren't included in the tests:

/account/confirm_email - Specific workflow and requires a key. Gives a 404
/icons - does nothing on its own; requires more after the /
/favorite - not sure, might require some specific workflow? Gives a 404
/layers/append - not sure, might require some specific workflow? Gives a missing argument error
map_detail, map_view, map_viewer, map_embed - Giving me the strange index out of bounds error. Might be fixable.

**Comment by davisc** [comment]
@travislbrundage The changes look fine, however, I question the reason for allowing trailing slash for all urls? I will pose the question in the general channel.

**Comment by travislbrundage** [comment]
I had just done that because I figured the problem would end up being more general when linking to mapstory. If you want a trailing slash to be allowed for map detail page, I would presume you want the same for the layer detail page since people may link to that as well. The same might be said for the profile page, etc... although, some pages it might not make sense. I figured at worst it wouldn't hurt anything since it is optional.

**Pull request merged**
