### PR TITLE
Add label tags to Content and StoryTeller UI

### PR DESCRIPTION
**Pull request by DavidJLee**
The check boxes in the content search and StoryTeller Filter pages are missing labels.

Missing a label prevents users from clicking the text to select the check box and raises accessibility issues.

I've added label tags and adjusted the styles to match how it displayed previously. This improves the usability of the interface as you can now click on the checkbox or the text to select it.

Two submodules were updated in the process. These could be excluded from the pull request if needed.

### CODE REVIEW

**Comment by Coop56** [comment]
In order to actually update the submodules you'd need to send in PRs on the actual sub projects themselves.  So we'll need to drop those changes.  Otherwise this looks fine.

**Comment by DavidJLee** [comment]
Ok, will drop the submodule changes out this afternoon.

**Comment by emilyashley** [comment]
Thanks y'all. I reviewed this last night as well and it looks good (sans the submodules)

**Comment by DavidJLee** [comment]
Backed out the submodule updates

**Review by emilyashley — APPROVED** [review]
Thanks!

**Pull request merged**
