### PR TITLE
Category persistence for maploom properties modal.

### LINKED ISSUE #1150: Category selection persistence for Story Property Modal in MapLoom
Currently in MapLoom, when you select and save a category to be associated with your story it succeeds in saving. However, if you reload the story config (refresh the page) the associated category is no longer selected on the front end from the dropdown menu in the story properties modal. 

This means if a user clicks 'save' to update other information without guaranteeing the previous (or a different) category is selected, the previously associated category is overwritten with None. 

And with the save button (or refreshing the page) being the only ways to dismiss the story properties modal we might be losing a bit of metadata on MapStories.

### PR DESCRIPTION
**Pull request by emilyashley**
Works with the front end changes here https://github.com/MapStory/MapLoom/commit/3ca2822a9e019c5d70af1a58313071bc90de2b5c to close https://github.com/MapStory/mapstory/issues/1150

Between these two commits, now:
— the category dropdown menu defaults to "-----" empty
— if there is a category saved to the story config in django, this will now be brought into the javascript scope and angular will auto-reselected this value in order to persist the data
— if you change a category selection and refresh the page, reopening the property modal will display your new data
— if you revoke a category and set it back to the default empty, this will also persist upon re-loading the story config

P.S. I also removed keywords and regions from this modal on this commit https://github.com/MapStory/MapLoom/commit/6d4931244e80946e70266ea32b4b6926debbe3d7

They could be set up in the future but for now they are also data lost / effort lost so I have removed them from user view. They really aren’t hooked up (and haven't been since I can remember) to the StoryService or the django model’s config jsons we send to maploom

### CODE REVIEW

**Review by Coop56 — APPROVED** [review]

**Comment by cuttlefish** [comment]
Should the maploom submodule be bumped?

**Comment by cuttlefish** [comment]
I'm going to add a few nitpicky comments. They have little to do with this PR and I don't expect them to get changed. I just want to discuss them.

**Review by cuttlefish — COMMENTED** [review]
(Lines 106 and 107. They weren't edited, so it's not showing up properly)
This doesn't seem to be returning a URL. It's returning a path. A URL would have a protocol and domain name (and possible user/pass) specified. e.g. `https://mapstory.org/story/`.
If you're _really_ bored you can check out the RFC
https://tools.ietf.org/html/rfc1738
https://en.wikipedia.org/wiki/URL

This is returning a `path` and should probably be called something like `get_absolute_path`.
For some examples in Django, see the following:
https://docs.djangoproject.com/en/2.0/ref/request-response/

This messed me up a few times when I was redoing the deployments. URL and path were used all over the place, often with the opposite meaning. Some of this may be coming from GeoNode... but we should try to be more consistent.

**Review by cuttlefish — COMMENTED** [review]
(Line 109) It seems odd to me that this is in the model. Shouldn't this be in a view?

Looking at the usage in other places, I _guess_ not. It just sounds a bit odd.

**Comment by cuttlefish** [comment]
@emilyashley Can you verify that the change I made still behaves correctly? I don't have a good way of testing it. I looked into adding a unit test and... became discouraged.
[This change was _definitely not_ made to pass the coverage tests. Nope, that would be irresponsible]

**Comment by cuttlefish** [comment]
I merged this so that I can update the MapLoom submodule. I'll make a new PR for that and then we can verify that your stuff worked on that.

**Pull request merged**
