### PR TITLE
Default ms style

### PR DESCRIPTION
**Pull request by goudine**
Re-issuing PR against `master` branch as was [discussed](https://github.com/MapStory/mapstory/pull/1221#issuecomment-361782512)

### CODE REVIEW

**Comment by cuttlefish** [comment]
Did the comments from #1221 get addressed?

**Comment by goudine** [comment]
@cuttlefish Yes, they have been addressed. Currently working on a test case

**Comment by cuttlefish** [comment]
@goudine Is this PR still being worked?

**Comment by emilyashley** [comment]
referencing this to #1209 & #1181

**Comment by Coop56** [comment]
This PR needs reopened with the solution we talked about on hangouts / Slack.  It should be branched from master.

**Pull request closed without merging**
