### PR TITLE
Small fixes: Typo on profile page for VTC, fixed redirect after delet…

### PR DESCRIPTION
**Pull request by travislbrundage**
…ing a map or layer

### CODE REVIEW

**Comment by garnertb** [comment]
The first commit duplicates views verbatim from GeoNode.  Can you just use the views in GeoNode instead?

**Comment by travislbrundage** [comment]
It actually isn't quite verbatim from GeoNode - I've changed where it redirects to after removing the map/layer. It does have a lot of duplicated code, but I'm not sure how else to change just that one line without needing to create an entirely new view. Is there a way to do that?

As a side note, this is actually already there in the code, I didn't know I had this PR open still. :/

**Comment by garnertb** [comment]
Ahh, I see.  You could just wrap the view in another function, catch the response and override the redirect.  Its times like these when I prefer class based views over functional views.

**Comment by travislbrundage** [comment]
Yeah, if it had used a class I would have known what to do, but unfortunately a lot of them are functional views. Good to know though, I hadn't thought about it like that, but I think I understand how that'd be done (or I can figure out it with some google-fu). Thanks for the advice. I'll look into making it cleaner as I'm cleaning up GeoNode commits.

**Pull request closed without merging**
